### ISSUE TITLE
Version 1.1.0 throwing Cannot find module 'ngx-translate-phraseapp'

### ISSUE THREAD

**Issue by dkimmich-onventis** [phrase/ngx-translate-phraseapp#45]
After updating to v1.1.0, I'm getting the following error in my application:

```
error TS2307: Cannot find module 'ngx-translate-phraseapp' or its corresponding type declarations.

import { initializePhraseAppEditor, PhraseAppCompiler } from 'ngx-translate-phraseapp';
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
```

This can be reproduced simply by creating a new Angular project and configuring the project according to the documentation.

It looks like instead of the built application, the [source code was published to npm](https://www.npmjs.com/package/ngx-translate-phraseapp?activeTab=code).

**Comment by flowreaction** [comment]
Hi and thanks for filing an issue. 
You are correct that the source code was mistakenly published. Should be fixed now with #44 v1.1.2 on NPM.

**Comment by dkimmich-onventis** [comment]
Can confirm that it works again with v1.1.2. Thanks for the quick fix!
